name: Test envr.ps1

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install zsh
      #   run: sudo apt update && sudo apt install zsh -y
      
      - name: Test bash on Ubuntu
        id: version
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "TEST_RESULT<<$EOF" >> $GITHUB_ENV
          tests/sh/bash.sh >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          
      - name: Test bash on Ubuntu badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: ubuntu_bash
          LABEL: Ubuntu bash
          STATUS: ${{ env.TEST_RESULT }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    strategy:
      matrix:
        os: [windows-latest, windows-2019, ubuntu-latest, ubuntu-20.04, macos-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Test PowerShell on ${{ matrix.os }}
        if: ${{ contains(matrix.os, 'windows') }}
        run: .\tests\windows\ps.ps1

      - name: Test bash on ${{ matrix.os }}
        if: ${{ !contains(matrix.os, 'windows') }}
        run: tests/sh/bash.sh

      - name: Install zsh on ${{ matrix.os }}
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt update && sudo apt install zsh -y

      - name: Test zsh on ${{ matrix.os }}
        if: ${{ !contains(matrix.os, 'windows') }}
        run: tests/sh/zsh.sh
